---

require: rubocop-rspec

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/BlockEndNewline:
  Enabled: true

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/DotPosition:
  EnforcedStyle: leading

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

# Use 2 spaces for indentation.
Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/LineLength:
  Max: 120
  Exclude:
  - "**/spec/**/*"

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
  IndentationWidth: 2

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceBeforeBrackets:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  AllowedMethods:
  - change
  - not_change

Lint/MissingSuper:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/SuppressedException:
  AllowComments: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 125

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  DisallowedExamples:
  - works
  - does not work
  - works as expected
  - does something
  - succeeds

RSpec/IndexedLet:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: true

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 8

RSpec/Pending:
  Enabled: true

RSpec/StubbedMock:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: false

Style/ArrayIntersect:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EndlessMethod:
  Enabled: true
  EnforcedStyle: disallow

Style/EvalWithLocation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/IfUnlessModifier:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: forbidden

Style/NumberedParametersLimit:
  Max: 2

Style/NumericPredicate:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/OptionalBooleanParameter:
  AllowedMethods:
  - perform
  - respond_to_missing?

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SlicingWithRange:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
